id: P001811
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 10:22:55.745367
source_metadata:
  id: bdr:W3CN6903
  title: གན་རྒྱའི་སྐོར་གྱི་བཅའ་ཁྲིམས།
  author: ''
  volumes:
    acbc7b034da24a1cbc7dac6a0ad575f0:
      image_group_id: I3CN6905
      title: ''
      volume_number: 1
      total_pages: 114
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
